### PR TITLE
Update block_attributes.json

### PR DESCRIPTION
**Pull request by smartcmd**
Using tool https://github.com/AllayMC/DataExtractor

### CODE REVIEW

**Comment by smartcmd** [comment]
@SupremeMortal Please check this if you have time :)

**Comment by smartcmd** [comment]
@Kazzuk Sorry for ping

**Comment by Kazzuk** [comment]
At some point I'd like to provide our own tool to generate this automatically. Regarding [Cloudburst Server](https://github.com/CloudburstMC/Server) I don't know what way we will be using block attributes API wise just yet.

**Comment by smartcmd** [comment]
> At some point I'd like to provide our own tool to generate this automatically. Regarding [Cloudburst Server](https://github.com/CloudburstMC/Server) I don't know what way we will be using block attributes API wise just yet.

ok

**Pull request closed without merging**
